# Accounting for Survivorship Bias

## Imports

In [2]:
import pandas as pd
import numpy as np

from trading_algos import datasets as tad

%load_ext autoreload
%autoreload 2

2026-03-14 10:03:04.138 | INFO     | trading_algos.config:<module>:11 - PROJ_ROOT path is: /home/jamie/code/JamieW365/trading_algos

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload

## Load Data

In [4]:
# Load the most recent S&P stock metadata
df_current = tad.get_sp500_meta()
df_current.head()

,Security,GICS Sector,GICS Sub-Industry,Headquarters Location,Date added,CIK,Founded
Symbol,,,,,,,
MMM,3M,Industrials,Industrial Conglomerates,"Saint Paul, Minnesota",1957-03-04,66740,1902
AOS,A. O. Smith,Industrials,Building Products,"Milwaukee, Wisconsin",2017-07-26,91142,1916
ABT,Abbott Laboratories,Health Care,Health Care Equipment,"North Chicago, Illinois",1957-03-04,1800,1888
ABBV,AbbVie,Health Care,Biotechnology,"North Chicago, Illinois",2012-12-31,1551152,2013 (1888)
ACN,Accenture,Information Technology,IT Consulting & Other Services,"Dublin, Ireland",2011-07-06,1467373,1989

In [6]:
tad.get_sp500_history(get_latest=True)

Effective Date      Added                                Removed  \
Effective Date     Ticker                       Security  Ticker
February 9, 2026     CIEN                          Ciena     DAY
December 22, 2025     CRH                            CRH     LKQ
December 22, 2025    CVNA                        Carvana    SOLS
December 22, 2025     FIX            Comfort Systems USA     MHK
December 11, 2025    ARES                Ares Management       K
...                   ...                            ...     ...
December 11, 1998    CPWR                      Compuware     SUN
June 17, 1997         CCR  Countrywide Credit Industries     USL
September 30, 1994    NCC                  National City     MCK
July 1, 1976          BUD                 Anheuser Busch     HNG
July 1, 1976          DIS        The Walt Disney Company     AYE

Effective Date                                   \
Effective Date                         Security
February 9, 2026                       Dayforce
December 22, 2025               LKQ Corporation
December 22, 2025   Solstice Advanced Materials
December 22, 2025             Mohawk Industries
December 11, 2025                     Kellanova
...                                         ...
December 11, 1998                    SunAmerica
June 17, 1997                            USLife
September 30, 1994                     McKesson
July 1, 1976                Houston Natural Gas
July 1, 1976                   Allegheny Energy

Effective Date                                                 Reason
Effective Date                                                 Reason
February 9, 2026               Thoma Bravo L.P. acquired Dayforce.[6]
December 22, 2025                    Market capitalization change.[7]
December 22, 2025                    Market capitalization change.[7]
December 22, 2025                    Market capitalization change.[7]
December 11, 2025                    Mars Inc. acquired Kellanova.[8]
...                                                               ...
December 11, 1998                      AIG purchased SunAmerica.[270]
June 17, 1997                               AIG acquired USLife.[271]
September 30, 1994  McKesson sold PCS Health Services to Eli Lilly...
July 1, 1976        Major restructuring of S&P 500 to have fewer i...
July 1, 1976        Major restructuring of S&P 500 to have fewer i...

[389 rows x 5 columns]

In [8]:
wiki = pd.read_html('https://en.wikipedia.org/wiki/List_of_S%26P_500_companies',
                                storage_options={'User-Agent': 'pandas'},
                                index_col=0)

In [10]:
type(wiki)

list

In [18]:
tad.get_sp500_meta()

Exception: HTTP Error 403: Forbidden

In [1]:
tad.get_sp500_meta()[0]

NameError: name 'tad' is not defined